# Generated by Django 4.1.13 on 2024-04-04 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published date')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image')),
                ('content', models.TextField(verbose_name='Content')),
                ('jenre', models.CharField(max_length=150, verbose_name='Jenre')),
                ('year', models.DateTimeField(default=datetime.datetime.now, verbose_name='Year')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('director', models.CharField(max_length=150, verbose_name='Director')),
            ],
        ),
    ]
